eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.181:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-feign1
  sleuth:
    feign:
      enabled: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,httptrace,logfile
#niws:
#  loadbalancer:
#    availabilityFilteringRule:
#      filterCircuitTripped: false