eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.181:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api1/**
      serviceId: service-hi
    api-b:
      path: /api2/**
      serviceId: service-feign1
    api-c:
      path: /graphql-test/**
      url: http://localhost:9000/graphql
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#  SendErrorFilter:
#    post:
#      disable: true
#feign:
#  hystrix:
#    enabled: true

#niws:
#  loadbalancer:
#    availabilityFilteringRule:
#      filterCircuitTripped: false