spring:
  application:
    name: eureka-server

server:
  port: 8782

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://192.168.3.181:8781/eureka/
  instance:
    preferIpAddress: true
    hostname: eureka-peer2
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
